// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "document_definition.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>

namespace Lux {
namespace Config {

namespace {

const ::google::protobuf::Descriptor* Field_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Field_reflection_ = NULL;
const ::google::protobuf::Descriptor* Field_Index_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Field_Index_reflection_ = NULL;
const ::google::protobuf::Descriptor* Field_AttrIndex_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Field_AttrIndex_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* Field_AttrIndexType_descriptor_ = NULL;
const ::google::protobuf::Descriptor* Document_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Document_reflection_ = NULL;

}  // namespace


void protobuf_BuildDesc_document_5fdefinition_2eproto_AssignGlobalDescriptors(const ::google::protobuf::FileDescriptor* file) {
  Field_descriptor_ = file->message_type(0);
  Field::default_instance_ = new Field();
  static const int Field_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Field, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Field, index_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Field, display_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Field, attr_index_),
  };
  Field_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Field_descriptor_,
      Field::default_instance_,
      Field_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Field, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Field, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(Field));
  Field_Index_descriptor_ = Field_descriptor_->nested_type(0);
  Field_Index::default_instance_ = new Field_Index();
  static const int Field_Index_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Field_Index, indexing_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Field_Index, index_to_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Field_Index, exact_),
  };
  Field_Index_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Field_Index_descriptor_,
      Field_Index::default_instance_,
      Field_Index_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Field_Index, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Field_Index, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(Field_Index));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Field_Index_descriptor_, Field_Index::default_instance_);
  Field_AttrIndex_descriptor_ = Field_descriptor_->nested_type(1);
  Field_AttrIndex::default_instance_ = new Field_AttrIndex();
  static const int Field_AttrIndex_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Field_AttrIndex, indexing_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Field_AttrIndex, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Field_AttrIndex, size_),
  };
  Field_AttrIndex_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Field_AttrIndex_descriptor_,
      Field_AttrIndex::default_instance_,
      Field_AttrIndex_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Field_AttrIndex, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Field_AttrIndex, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(Field_AttrIndex));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Field_AttrIndex_descriptor_, Field_AttrIndex::default_instance_);
  Field_AttrIndexType_descriptor_ = Field_descriptor_->enum_type(0);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Field_descriptor_, Field::default_instance_);
  Document_descriptor_ = file->message_type(1);
  Document::default_instance_ = new Document();
  static const int Document_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Document, field_),
  };
  Document_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Document_descriptor_,
      Document::default_instance_,
      Document_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Document, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Document, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(Document));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Document_descriptor_, Document::default_instance_);
  Field::default_instance_->InitAsDefaultInstance();
  Field_Index::default_instance_->InitAsDefaultInstance();
  Field_AttrIndex::default_instance_->InitAsDefaultInstance();
  Document::default_instance_->InitAsDefaultInstance();
}

void protobuf_BuildDesc_document_5fdefinition_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  pool->InternalBuildGeneratedFile(
    "\n\031document_definition.proto\022\nLux.Config\""
    "\333\002\n\005Field\022\014\n\004name\030\001 \002(\t\022&\n\005index\030\002 \001(\0132\027"
    ".Lux.Config.Field.Index\022\026\n\007display\030\003 \001(\010"
    ":\005false\022/\n\nattr_index\030\004 \001(\0132\033.Lux.Config"
    ".Field.AttrIndex\032J\n\005Index\022\020\n\010indexing\030\001 "
    "\002(\010\022\031\n\010index_to\030\002 \002(\t:\007default\022\024\n\005exact\030"
    "\003 \001(\010:\005false\032a\n\tAttrIndex\022\027\n\010indexing\030\001 "
    "\002(\010:\005false\022-\n\004type\030\002 \002(\0162\037.Lux.Config.Fi"
    "eld.AttrIndexType\022\014\n\004size\030\003 \002(\r\"$\n\rAttrI"
    "ndexType\022\n\n\006STRING\020\000\022\007\n\003INT\020\001\",\n\010Documen"
    "t\022 \n\005field\030\001 \003(\0132\021.Lux.Config.Field", 435,
  &protobuf_BuildDesc_document_5fdefinition_2eproto_AssignGlobalDescriptors);
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_document_5fdefinition_2eproto {
  StaticDescriptorInitializer_document_5fdefinition_2eproto() {
    protobuf_BuildDesc_document_5fdefinition_2eproto();
  }
} static_descriptor_initializer_document_5fdefinition_2eproto_;


// ===================================================================

const ::google::protobuf::EnumDescriptor* Field_AttrIndexType_descriptor() {
  if (Field_AttrIndexType_descriptor_ == NULL) protobuf_BuildDesc_document_5fdefinition_2eproto();
  return Field_AttrIndexType_descriptor_;
}
bool Field_AttrIndexType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const Field_AttrIndexType Field::STRING;
const Field_AttrIndexType Field::INT;
const Field_AttrIndexType Field::AttrIndexType_MIN;
const Field_AttrIndexType Field::AttrIndexType_MAX;
#endif  // _MSC_VER

const ::std::string Field_Index::_default_index_to_("default");

Field_Index::Field_Index()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    indexing_(false),
    index_to_(const_cast< ::std::string*>(&_default_index_to_)),
    exact_(false) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void Field_Index::InitAsDefaultInstance() {}

Field_Index::Field_Index(const Field_Index& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    indexing_(false),
    index_to_(const_cast< ::std::string*>(&_default_index_to_)),
    exact_(false) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

Field_Index::~Field_Index() {
  if (index_to_ != &_default_index_to_) {
    delete index_to_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* Field_Index::descriptor() {
  if (Field_Index_descriptor_ == NULL) protobuf_BuildDesc_document_5fdefinition_2eproto();
  return Field_Index_descriptor_;
}

const Field_Index& Field_Index::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_document_5fdefinition_2eproto();
  return *default_instance_;
}

Field_Index* Field_Index::default_instance_ = NULL;

Field_Index* Field_Index::New() const {
  return new Field_Index;
}

const ::google::protobuf::Descriptor* Field_Index::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* Field_Index::GetReflection() const {
  if (Field_Index_reflection_ == NULL) protobuf_BuildDesc_document_5fdefinition_2eproto();
  return Field_Index_reflection_;
}

// -------------------------------------------------------------------




Field_AttrIndex::Field_AttrIndex()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    indexing_(false),
    type_(0),
    size_(0u) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void Field_AttrIndex::InitAsDefaultInstance() {}

Field_AttrIndex::Field_AttrIndex(const Field_AttrIndex& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    indexing_(false),
    type_(0),
    size_(0u) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

Field_AttrIndex::~Field_AttrIndex() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* Field_AttrIndex::descriptor() {
  if (Field_AttrIndex_descriptor_ == NULL) protobuf_BuildDesc_document_5fdefinition_2eproto();
  return Field_AttrIndex_descriptor_;
}

const Field_AttrIndex& Field_AttrIndex::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_document_5fdefinition_2eproto();
  return *default_instance_;
}

Field_AttrIndex* Field_AttrIndex::default_instance_ = NULL;

Field_AttrIndex* Field_AttrIndex::New() const {
  return new Field_AttrIndex;
}

const ::google::protobuf::Descriptor* Field_AttrIndex::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* Field_AttrIndex::GetReflection() const {
  if (Field_AttrIndex_reflection_ == NULL) protobuf_BuildDesc_document_5fdefinition_2eproto();
  return Field_AttrIndex_reflection_;
}

// -------------------------------------------------------------------

const ::std::string Field::_default_name_;



Field::Field()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    name_(const_cast< ::std::string*>(&_default_name_)),
    index_(NULL),
    display_(false),
    attr_index_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void Field::InitAsDefaultInstance() {  index_ = const_cast< ::Lux::Config::Field_Index*>(&::Lux::Config::Field_Index::default_instance());
  attr_index_ = const_cast< ::Lux::Config::Field_AttrIndex*>(&::Lux::Config::Field_AttrIndex::default_instance());
}

Field::Field(const Field& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    name_(const_cast< ::std::string*>(&_default_name_)),
    index_(NULL),
    display_(false),
    attr_index_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

Field::~Field() {
  if (name_ != &_default_name_) {
    delete name_;
  }
  if (this != default_instance_) {
    delete index_;
    delete attr_index_;
  }
}

const ::google::protobuf::Descriptor* Field::descriptor() {
  if (Field_descriptor_ == NULL) protobuf_BuildDesc_document_5fdefinition_2eproto();
  return Field_descriptor_;
}

const Field& Field::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_document_5fdefinition_2eproto();
  return *default_instance_;
}

Field* Field::default_instance_ = NULL;

Field* Field::New() const {
  return new Field;
}

const ::google::protobuf::Descriptor* Field::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* Field::GetReflection() const {
  if (Field_reflection_ == NULL) protobuf_BuildDesc_document_5fdefinition_2eproto();
  return Field_reflection_;
}

// ===================================================================


Document::Document()
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void Document::InitAsDefaultInstance() {}

Document::Document(const Document& from)
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

Document::~Document() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* Document::descriptor() {
  if (Document_descriptor_ == NULL) protobuf_BuildDesc_document_5fdefinition_2eproto();
  return Document_descriptor_;
}

const Document& Document::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_document_5fdefinition_2eproto();
  return *default_instance_;
}

Document* Document::default_instance_ = NULL;

Document* Document::New() const {
  return new Document;
}

const ::google::protobuf::Descriptor* Document::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* Document::GetReflection() const {
  if (Document_reflection_ == NULL) protobuf_BuildDesc_document_5fdefinition_2eproto();
  return Document_reflection_;
}

}  // namespace Config
}  // namespace Lux
